from flask_wtf import FlaskForm
from wtforms import SubmitField, DecimalField
from wtforms.validators import DataRequired

class Parameter2012Form(FlaskForm):
    R1popRatio = DecimalField('R1 Population Ratio', validators=[DataRequired()])
    R2popRatio = DecimalField('R2 Population Ratio', validators=[DataRequired()])
    growthRate = DecimalField('Growth Rate', validators=[DataRequired()])
    S_D1senRatio = DecimalField('Sensitivity of S to D1 relative to growth rate', validators=[DataRequired()])
    S_D2senRatio = DecimalField('Sensitivity of S to D2 relative to sensitivity to D1', validators=[DataRequired()])
    R1_D1senRatio = DecimalField('Sensitivity of R1 to D1 over sensitivity of S to D1', validators=[DataRequired()])
    R2_D2senRatio = DecimalField('Sensitivity of R2 to D2 over the sensitivity of S to D2', validators=[DataRequired()])
    S_to_R1 = DecimalField('S transition to R1', validators=[DataRequired()])
    S_to_R2 = DecimalField('S transition to R2', validators=[DataRequired()])
    submit = SubmitField('Submit Parameters')

class FullParameterForm(FlaskForm):
    Spop = DecimalField('S Population', validators=[DataRequired()])
    R1pop = DecimalField('R1 Population', validators=[DataRequired()])
    R2pop = DecimalField('R2 Population', validators=[DataRequired()])
    R12pop = DecimalField('R12 Population', validators=[DataRequired()])
    growthRate = DecimalField('Growth Rate', validators=[DataRequired()])
    S_D1sensitivity = DecimalField('Base D1 sensitiviety', validators=[DataRequired()])
    S_D2sensitivity = DecimalField('Base D2 sensitiviety', validators=[DataRequired()])    
    R1_D1sensitivity = DecimalField('R1 D1 sensitiviety', validators=[DataRequired()])
    R1_D2sensitivity = DecimalField('R1 D2 sensitiviety', validators=[DataRequired()])    
    R2_D1sensitivity = DecimalField('R2 D1 sensitiviety', validators=[DataRequired()])
    R2_D2sensitivity = DecimalField('R2 D2 sensitiviety', validators=[DataRequired()])    
    R12_D1sensitivity = DecimalField('R12 D1 sensitiviety', validators=[DataRequired()])
    R12_D2sensitivity = DecimalField('R12 D2 sensitiviety', validators=[DataRequired()])    
    S_to_S = DecimalField('S Self Transition', validators=[DataRequired()])
    S_to_R1 = DecimalField('S transition to R1', validators=[DataRequired()])
    S_to_R2 = DecimalField('S transition to R2', validators=[DataRequired()])
    S_to_R12 = DecimalField('S transition to R12', validators=[DataRequired()])
    R1_to_S = DecimalField('R1 transition to S', validators=[DataRequired()])
    R1_to_R1 = DecimalField('R1 self Transition', validators=[DataRequired()])
    R1_to_R2 = DecimalField('R1 transition to R2', validators=[DataRequired()])
    R1_to_R12 = DecimalField('R1 transition to R12', validators=[DataRequired()])
    R2_to_S = DecimalField('R2 transition to S', validators=[DataRequired()])
    R2_to_R1 = DecimalField('R2 transition to R1', validators=[DataRequired()])
    R2_to_R2 = DecimalField('R2 self transition', validators=[DataRequired()])
    R2_to_R12 = DecimalField('R2 transition to R12', validators=[DataRequired()])
    R12_to_S = DecimalField('R12 transition to S', validators=[DataRequired()])
    R12_to_R1 = DecimalField('R12 transition to R1', validators=[DataRequired()])
    R12_to_R2 = DecimalField('R12 transition to R2', validators=[DataRequired()])
    R12_to_R12 = DecimalField('R2 self transition', validators=[DataRequired()])
    submit = SubmitField('Submit Parameters')
