from flask_wtf import FlaskForm
from wtforms import SubmitField, DecimalField, FloatField, StringField
from wtforms.validators import DataRequired

class PNAS2012_OutcomeFilterForm(FlaskForm):
    baseSurvival_min = FloatField('Survival Range (days) on Standard Precision Medicine',default = 0.0)
    baseSurvival_max = FloatField('Survival Range (days) on Standard Precision Medicine',default = 1845.0, validators=[DataRequired()])
    submit = SubmitField('Submit Parameters')
    
class PNAS2012_InputParamsForm(FlaskForm):
    R1popRatio_min = FloatField('R1 Population Ratio', default = 0, validators=[DataRequired()])
    R1popRatio_max = FloatField('R1 Population Ratio', default = 0.9, validators=[DataRequired()])
    R2popRatio_min = FloatField('R2 Population Ratio', default = 0, validators=[DataRequired()])
    R2popRatio_max = FloatField('R2 Population Ratio', default = 0.9, validators=[DataRequired()])
    growthRate_min = FloatField('Growth Rate', default = 0.001, validators=[DataRequired()])
    growthRate_max = FloatField('Growth Rate', default = 0.34, validators=[DataRequired()])
    S_D1senRatio_min = FloatField('Sensitivity of S to D1 relative to growth rate', default = 0.000560, validators=[DataRequired()])
    S_D1senRatio_max = FloatField('Sensitivity of S to D1 relative to growth rate', default = 440, validators=[DataRequired()])
    S_D2senRatio_min = FloatField('Sensitivity of S to D2 relative to sensitivity to D1', default = 0.0004, validators=[DataRequired()])
    S_D2senRatio_max = FloatField('Sensitivity of S to D2 relative to sensitivity to D1', default = 1, validators=[DataRequired()])
    R1_D1senRatio_min = FloatField('Sensitivity of R1 to D1 over sensitivity of S to D1', default = 0, validators=[DataRequired()])
    R1_D1senRatio_max = FloatField('Sensitivity of R1 to D1 over sensitivity of S to D1', default = 0.8, validators=[DataRequired()])
    R2_D2senRatio_min = FloatField('Sensitivity of R2 to D2 over the sensitivity of S to D2', default = 0, validators=[DataRequired()])
    R2_D2senRatio_max = FloatField('Sensitivity of R2 to D2 over the sensitivity of S to D2', default = 0.8, validators=[DataRequired()])
    S_to_R1_min = FloatField('S transition to R1', default = 0.00000000001, validators=[DataRequired()])
    S_to_R1_max = FloatField('S transition to R1', default = 0.001, validators=[DataRequired()])
    S_to_R2_min = FloatField('S transition to R2', default = 0.00000000001, validators=[DataRequired()])
    S_to_R2_max = FloatField('S transition to R2', default = 0.001, validators=[DataRequired()])
    submit = SubmitField('Submit Parameters')

class PNAS2012_FullParamsForm(FlaskForm):
    Spop_min = FloatField('S Population', validators=[DataRequired()])
    Spop_max = FloatField('S Population', validators=[DataRequired()])
    R1pop_min = FloatField('R1 Population', validators=[DataRequired()])
    R1pop_max = FloatField('R1 Population', validators=[DataRequired()])
    R2pop_min = FloatField('R2 Population', validators=[DataRequired()])
    R2pop_max = FloatField('R2 Population', validators=[DataRequired()])
    R12pop_min = FloatField('R12 Population', validators=[DataRequired()])
    R12pop_max = FloatField('R12 Population', validators=[DataRequired()])
    growthRate_min = FloatField('Growth Rate', validators=[DataRequired()])
    growthRate_max = FloatField('Growth Rate', validators=[DataRequired()])
    S_D1sensitivity_min = FloatField('Base D1 sensitiviety', validators=[DataRequired()])
    S_D1sensitivity_max = FloatField('Base D1 sensitiviety', validators=[DataRequired()])
    S_D2sensitivity_min = FloatField('Base D2 sensitiviety', validators=[DataRequired()])
    S_D2sensitivity_max = FloatField('Base D2 sensitiviety', validators=[DataRequired()])    
    R1_D1sensitivity_min = FloatField('R1 D1 sensitiviety', validators=[DataRequired()])
    R1_D1sensitivity_max = FloatField('R1 D1 sensitiviety', validators=[DataRequired()])
    R1_D2sensitivity_min = FloatField('R1 D2 sensitiviety', validators=[DataRequired()])
    R1_D2sensitivity_max = FloatField('R1 D2 sensitiviety', validators=[DataRequired()])    
    R2_D1sensitivity_min = FloatField('R2 D1 sensitiviety', validators=[DataRequired()])
    R2_D1sensitivity_max = FloatField('R2 D1 sensitiviety', validators=[DataRequired()])
    R2_D2sensitivity_min = FloatField('R2 D2 sensitiviety', validators=[DataRequired()])
    R2_D2sensitivity_max = FloatField('R2 D2 sensitiviety', validators=[DataRequired()])    
    R12_D1sensitivity_min = FloatField('R12 D1 sensitiviety', validators=[DataRequired()])
    R12_D1sensitivity_max = FloatField('R12 D1 sensitiviety', validators=[DataRequired()])
    R12_D2sensitivity_min = FloatField('R12 D2 sensitiviety', validators=[DataRequired()])
    R12_D2sensitivity_max = FloatField('R12 D2 sensitiviety', validators=[DataRequired()])    
    S_to_S_min = FloatField('S Self Transition', validators=[DataRequired()])
    S_to_S_max = FloatField('S Self Transition', validators=[DataRequired()])
    S_to_R1_min = FloatField('S transition to R1', validators=[DataRequired()])
    S_to_R1_max = FloatField('S transition to R1', validators=[DataRequired()])
    S_to_R2_min = FloatField('S transition to R2', validators=[DataRequired()])
    S_to_R2_max = FloatField('S transition to R2', validators=[DataRequired()])
    S_to_R12_min = FloatField('S transition to R12', validators=[DataRequired()])
    S_to_R12_max = FloatField('S transition to R12', validators=[DataRequired()])
    R1_to_S_min = FloatField('R1 transition to S', validators=[DataRequired()])
    R1_to_S_max = FloatField('R1 transition to S', validators=[DataRequired()])
    R1_to_R1_min = FloatField('R1 self Transition', validators=[DataRequired()])
    R1_to_R1_max = FloatField('R1 self Transition', validators=[DataRequired()])
    R1_to_R2_min = FloatField('R1 transition to R2', validators=[DataRequired()])
    R1_to_R2_max = FloatField('R1 transition to R2', validators=[DataRequired()])
    R1_to_R12_min = FloatField('R1 transition to R12', validators=[DataRequired()])
    R1_to_R12_max = FloatField('R1 transition to R12', validators=[DataRequired()])
    R2_to_S_min = FloatField('R2 transition to S', validators=[DataRequired()])
    R2_to_S_max = FloatField('R2 transition to S', validators=[DataRequired()])
    R2_to_R1_min = FloatField('R2 transition to R1', validators=[DataRequired()])
    R2_to_R1_max = FloatField('R2 transition to R1', validators=[DataRequired()])
    R2_to_R2_min = FloatField('R2 self transition', validators=[DataRequired()])
    R2_to_R2_max = FloatField('R2 self transition', validators=[DataRequired()])
    R2_to_R12_min = FloatField('R2 transition to R12', validators=[DataRequired()])
    R2_to_R12_max = FloatField('R2 transition to R12', validators=[DataRequired()])
    R12_to_S_min = FloatField('R12 transition to S', validators=[DataRequired()])
    R12_to_S_max = FloatField('R12 transition to S', validators=[DataRequired()])
    R12_to_R1_min = FloatField('R12 transition to R1', validators=[DataRequired()])
    R12_to_R1_max = FloatField('R12 transition to R1', validators=[DataRequired()])
    R12_to_R2_min = FloatField('R12 transition to R2', validators=[DataRequired()])
    R12_to_R2_max = FloatField('R12 transition to R2', validators=[DataRequired()])
    R12_to_R12_min = FloatField('R2 self transition', validators=[DataRequired()])
    R12_to_R12_max = FloatField('R2 self transition', validators=[DataRequired()])
    submit = SubmitField('Submit Parameters')

#class PNAS2012_StrategyForm(FlaskForm):
    
