"""Add parameter foreign key to simulation output

Revision ID: 11edf4a599b6
Revises: 6e5a69aaebc8
Create Date: 2022-05-17 11:14:57.130853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11edf4a599b6'
down_revision = '6e5a69aaebc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('simulation_output_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parameters', 'simulation_output', ['simulation_output_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parameters', type_='foreignkey')
    op.drop_column('parameters', 'simulation_output_id')
    # ### end Alembic commands ###
