"""Rename categorization columns

Revision ID: 14218333ed6a
Revises: e2b298e4eba0
Create Date: 2022-06-23 07:12:06.546922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14218333ed6a"
down_revision = "e2b298e4eba0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drug_categorizations",
        sa.Column("standard_drug1_t0", sa.Integer(), nullable=True),
    )
    op.add_column(
        "drug_categorizations",
        sa.Column("standard_drug2_t0", sa.Integer(), nullable=True),
    )
    op.add_column(
        "drug_categorizations", sa.Column("dpm_drug1_t0", sa.Integer(), nullable=True)
    )
    op.add_column(
        "drug_categorizations", sa.Column("dpm_drug2_t0", sa.Integer(), nullable=True)
    )
    op.add_column(
        "drug_categorizations",
        sa.Column("standard_drug1_t45", sa.Integer(), nullable=True),
    )
    op.add_column(
        "drug_categorizations",
        sa.Column("standard_drug2_t45", sa.Integer(), nullable=True),
    )
    op.add_column(
        "drug_categorizations", sa.Column("dpm_drug1_t45", sa.Integer(), nullable=True)
    )
    op.add_column(
        "drug_categorizations", sa.Column("dpm_drug2_t45", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "drug_categorizations_t_0_dosage_1_fkey",
        "drug_categorizations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "drug_categorizations_t_0_dosage_2_fkey",
        "drug_categorizations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "drug_categorizations_t_45_dosage_1_fkey",
        "drug_categorizations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "drug_categorizations_t_45_dosage_2_fkey",
        "drug_categorizations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "drug_categorizations", "drug_dosages", ["standard_drug1_t0"], ["id"]
    )
    op.create_foreign_key(
        None, "drug_categorizations", "drug_dosages", ["dpm_drug2_t45"], ["id"]
    )
    op.create_foreign_key(
        None, "drug_categorizations", "drug_dosages", ["standard_drug2_t45"], ["id"]
    )
    op.create_foreign_key(
        None, "drug_categorizations", "drug_dosages", ["standard_drug2_t0"], ["id"]
    )
    op.create_foreign_key(
        None, "drug_categorizations", "drug_dosages", ["dpm_drug1_t45"], ["id"]
    )
    op.create_foreign_key(
        None, "drug_categorizations", "drug_dosages", ["dpm_drug1_t0"], ["id"]
    )
    op.create_foreign_key(
        None, "drug_categorizations", "drug_dosages", ["dpm_drug2_t0"], ["id"]
    )
    op.create_foreign_key(
        None, "drug_categorizations", "drug_dosages", ["standard_drug1_t45"], ["id"]
    )
    op.drop_column("drug_categorizations", "t_0_dosage_1")
    op.drop_column("drug_categorizations", "t_45_dosage_2")
    op.drop_column("drug_categorizations", "t_0_dosage_2")
    op.drop_column("drug_categorizations", "t_45_dosage_1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drug_categorizations",
        sa.Column("t_45_dosage_1", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "drug_categorizations",
        sa.Column("t_0_dosage_2", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "drug_categorizations",
        sa.Column("t_45_dosage_2", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "drug_categorizations",
        sa.Column("t_0_dosage_1", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "drug_categorizations", type_="foreignkey")
    op.drop_constraint(None, "drug_categorizations", type_="foreignkey")
    op.drop_constraint(None, "drug_categorizations", type_="foreignkey")
    op.drop_constraint(None, "drug_categorizations", type_="foreignkey")
    op.drop_constraint(None, "drug_categorizations", type_="foreignkey")
    op.drop_constraint(None, "drug_categorizations", type_="foreignkey")
    op.drop_constraint(None, "drug_categorizations", type_="foreignkey")
    op.drop_constraint(None, "drug_categorizations", type_="foreignkey")
    op.create_foreign_key(
        "drug_categorizations_t_45_dosage_2_fkey",
        "drug_categorizations",
        "drug_dosages",
        ["t_45_dosage_2"],
        ["id"],
    )
    op.create_foreign_key(
        "drug_categorizations_t_45_dosage_1_fkey",
        "drug_categorizations",
        "drug_dosages",
        ["t_45_dosage_1"],
        ["id"],
    )
    op.create_foreign_key(
        "drug_categorizations_t_0_dosage_2_fkey",
        "drug_categorizations",
        "drug_dosages",
        ["t_0_dosage_2"],
        ["id"],
    )
    op.create_foreign_key(
        "drug_categorizations_t_0_dosage_1_fkey",
        "drug_categorizations",
        "drug_dosages",
        ["t_0_dosage_1"],
        ["id"],
    )
    op.drop_column("drug_categorizations", "dpm_drug2_t45")
    op.drop_column("drug_categorizations", "dpm_drug1_t45")
    op.drop_column("drug_categorizations", "standard_drug2_t45")
    op.drop_column("drug_categorizations", "standard_drug1_t45")
    op.drop_column("drug_categorizations", "dpm_drug2_t0")
    op.drop_column("drug_categorizations", "dpm_drug1_t0")
    op.drop_column("drug_categorizations", "standard_drug2_t0")
    op.drop_column("drug_categorizations", "standard_drug1_t0")
    # ### end Alembic commands ###
