"""Update drug categorization table fields

Revision ID: 194f50aadb53
Revises: 14218333ed6a
Create Date: 2022-06-23 13:56:29.131921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "194f50aadb53"
down_revision = "14218333ed6a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drug_categorizations", sa.Column("standard_t0", sa.Integer(), nullable=True)
    )
    op.add_column(
        "drug_categorizations", sa.Column("dpm_t0", sa.Integer(), nullable=True)
    )
    op.add_column(
        "drug_categorizations", sa.Column("standard_t45", sa.Integer(), nullable=True)
    )
    op.add_column(
        "drug_categorizations", sa.Column("dpm_t45", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "drug_categorizations_standard_drug2_t0_fkey",
        "drug_categorizations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "drug_categorizations_dpm_drug2_t0_fkey",
        "drug_categorizations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "drug_categorizations_standard_drug1_t0_fkey",
        "drug_categorizations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "drug_categorizations_standard_drug2_t45_fkey",
        "drug_categorizations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "drug_categorizations_standard_drug1_t45_fkey",
        "drug_categorizations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "drug_categorizations_dpm_drug1_t0_fkey",
        "drug_categorizations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "drug_categorizations_dpm_drug2_t45_fkey",
        "drug_categorizations",
        type_="foreignkey",
    )
    op.drop_constraint(
        "drug_categorizations_dpm_drug1_t45_fkey",
        "drug_categorizations",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "drug_categorizations", "drug_dosages", ["dpm_t45"], ["id"]
    )
    op.create_foreign_key(
        None, "drug_categorizations", "drug_dosages", ["standard_t45"], ["id"]
    )
    op.create_foreign_key(
        None, "drug_categorizations", "drug_dosages", ["dpm_t0"], ["id"]
    )
    op.create_foreign_key(
        None, "drug_categorizations", "drug_dosages", ["standard_t0"], ["id"]
    )
    op.drop_column("drug_categorizations", "standard_drug2_t0")
    op.drop_column("drug_categorizations", "dpm_drug1_t45")
    op.drop_column("drug_categorizations", "dpm_drug2_t0")
    op.drop_column("drug_categorizations", "standard_drug1_t45")
    op.drop_column("drug_categorizations", "standard_drug1_t0")
    op.drop_column("drug_categorizations", "dpm_drug2_t45")
    op.drop_column("drug_categorizations", "dpm_drug1_t0")
    op.drop_column("drug_categorizations", "standard_drug2_t45")
    op.drop_index("ix_populations_r1", table_name="populations")
    op.drop_index("ix_populations_r12", table_name="populations")
    op.drop_index("ix_populations_r2", table_name="populations")
    op.drop_index("ix_populations_s", table_name="populations")
    op.drop_column("populations", "s")
    op.drop_column("populations", "r2")
    op.drop_column("populations", "r12")
    op.drop_column("populations", "r1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "populations", sa.Column("r1", sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "populations",
        sa.Column("r12", sa.NUMERIC(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "populations", sa.Column("r2", sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "populations", sa.Column("s", sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_populations_s", "populations", ["s"], unique=False)
    op.create_index("ix_populations_r2", "populations", ["r2"], unique=False)
    op.create_index("ix_populations_r12", "populations", ["r12"], unique=False)
    op.create_index("ix_populations_r1", "populations", ["r1"], unique=False)
    op.add_column(
        "drug_categorizations",
        sa.Column(
            "standard_drug2_t45", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "drug_categorizations",
        sa.Column("dpm_drug1_t0", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "drug_categorizations",
        sa.Column("dpm_drug2_t45", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "drug_categorizations",
        sa.Column(
            "standard_drug1_t0", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "drug_categorizations",
        sa.Column(
            "standard_drug1_t45", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "drug_categorizations",
        sa.Column("dpm_drug2_t0", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "drug_categorizations",
        sa.Column("dpm_drug1_t45", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "drug_categorizations",
        sa.Column(
            "standard_drug2_t0", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "drug_categorizations", type_="foreignkey")
    op.drop_constraint(None, "drug_categorizations", type_="foreignkey")
    op.drop_constraint(None, "drug_categorizations", type_="foreignkey")
    op.drop_constraint(None, "drug_categorizations", type_="foreignkey")
    op.create_foreign_key(
        "drug_categorizations_dpm_drug1_t45_fkey",
        "drug_categorizations",
        "drug_dosages",
        ["dpm_drug1_t45"],
        ["id"],
    )
    op.create_foreign_key(
        "drug_categorizations_dpm_drug2_t45_fkey",
        "drug_categorizations",
        "drug_dosages",
        ["dpm_drug2_t45"],
        ["id"],
    )
    op.create_foreign_key(
        "drug_categorizations_dpm_drug1_t0_fkey",
        "drug_categorizations",
        "drug_dosages",
        ["dpm_drug1_t0"],
        ["id"],
    )
    op.create_foreign_key(
        "drug_categorizations_standard_drug1_t45_fkey",
        "drug_categorizations",
        "drug_dosages",
        ["standard_drug1_t45"],
        ["id"],
    )
    op.create_foreign_key(
        "drug_categorizations_standard_drug2_t45_fkey",
        "drug_categorizations",
        "drug_dosages",
        ["standard_drug2_t45"],
        ["id"],
    )
    op.create_foreign_key(
        "drug_categorizations_standard_drug1_t0_fkey",
        "drug_categorizations",
        "drug_dosages",
        ["standard_drug1_t0"],
        ["id"],
    )
    op.create_foreign_key(
        "drug_categorizations_dpm_drug2_t0_fkey",
        "drug_categorizations",
        "drug_dosages",
        ["dpm_drug2_t0"],
        ["id"],
    )
    op.create_foreign_key(
        "drug_categorizations_standard_drug2_t0_fkey",
        "drug_categorizations",
        "drug_dosages",
        ["standard_drug2_t0"],
        ["id"],
    )
    op.drop_column("drug_categorizations", "dpm_t45")
    op.drop_column("drug_categorizations", "standard_t45")
    op.drop_column("drug_categorizations", "dpm_t0")
    op.drop_column("drug_categorizations", "standard_t0")
    # ### end Alembic commands ###
