"""Create stopping times table

Revision ID: 21e0dddf3272
Revises: 410779c77290
Create Date: 2022-05-31 09:20:05.228516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21e0dddf3272"
down_revision = "410779c77290"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stopping_times",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parameter_id", sa.Integer(), nullable=True),
        sa.Column("strategy_0", sa.Numeric(), nullable=True),
        sa.Column("strategy_1", sa.Numeric(), nullable=True),
        sa.Column("strategy_2_1", sa.Numeric(), nullable=True),
        sa.Column("strategy_2_2", sa.Numeric(), nullable=True),
        sa.Column("strategy_3", sa.Numeric(), nullable=True),
        sa.Column("strategy_1_dp", sa.Numeric(), nullable=True),
        sa.Column("strategy_2_1_dp", sa.Numeric(), nullable=True),
        sa.Column("strategy_2_2_dp", sa.Numeric(), nullable=True),
        sa.Column("strategy_3_dp", sa.Numeric(), nullable=True),
        sa.Column("global_dp", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(["parameter_id"], ["parameters.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stopping_times_global_dp"),
        "stopping_times",
        ["global_dp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_0"),
        "stopping_times",
        ["strategy_0"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_1"),
        "stopping_times",
        ["strategy_1"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_1_dp"),
        "stopping_times",
        ["strategy_1_dp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_2_1"),
        "stopping_times",
        ["strategy_2_1"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_2_1_dp"),
        "stopping_times",
        ["strategy_2_1_dp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_2_2"),
        "stopping_times",
        ["strategy_2_2"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_2_2_dp"),
        "stopping_times",
        ["strategy_2_2_dp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_3"),
        "stopping_times",
        ["strategy_3"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_3_dp"),
        "stopping_times",
        ["strategy_3_dp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stopping_times_strategy_3_dp"), table_name="stopping_times")
    op.drop_index(op.f("ix_stopping_times_strategy_3"), table_name="stopping_times")
    op.drop_index(
        op.f("ix_stopping_times_strategy_2_2_dp"), table_name="stopping_times"
    )
    op.drop_index(op.f("ix_stopping_times_strategy_2_2"), table_name="stopping_times")
    op.drop_index(
        op.f("ix_stopping_times_strategy_2_1_dp"), table_name="stopping_times"
    )
    op.drop_index(op.f("ix_stopping_times_strategy_2_1"), table_name="stopping_times")
    op.drop_index(op.f("ix_stopping_times_strategy_1_dp"), table_name="stopping_times")
    op.drop_index(op.f("ix_stopping_times_strategy_1"), table_name="stopping_times")
    op.drop_index(op.f("ix_stopping_times_strategy_0"), table_name="stopping_times")
    op.drop_index(op.f("ix_stopping_times_global_dp"), table_name="stopping_times")
    op.drop_table("stopping_times")
    # ### end Alembic commands ###
