"""Initial db creation with SimulationTypes, Parameters, SimulationOutput, and Strategy tables

Revision ID: 28eddb98acbd
Revises: 
Create Date: 2022-05-12 10:34:03.726824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28eddb98acbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy')
    op.drop_table('simulation_types')
    op.drop_table('simulation_output')
    op.drop_table('parameters')
    # ### end Alembic commands ###
