"""Add name field to strategies table

Revision ID: 2cad1a2a27f3
Revises: fec1154090c0
Create Date: 2022-05-31 17:54:28.987701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2cad1a2a27f3"
down_revision = "fec1154090c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("strategies", sa.Column("name", sa.String(length=128), nullable=True))
    op.create_index(op.f("ix_strategies_name"), "strategies", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_strategies_name"), table_name="strategies")
    op.drop_column("strategies", "name")
    # ### end Alembic commands ###
