"""Add drug categorization table

Revision ID: 2d551030b847
Revises: b9fd6bcd50e2
Create Date: 2022-06-22 21:30:42.930466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d551030b847"
down_revision = "b9fd6bcd50e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drug_categorizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=True),
        sa.Column("t_0_dosage_1", sa.Integer(), nullable=True),
        sa.Column("t_0_dosage_2", sa.Integer(), nullable=True),
        sa.Column("t_45_dosage_1", sa.Integer(), nullable=True),
        sa.Column("t_45_dosage_2", sa.Integer(), nullable=True),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["t_0_dosage_1"],
            ["drug_dosages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["t_0_dosage_2"],
            ["drug_dosages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["t_45_dosage_1"],
            ["drug_dosages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["t_45_dosage_2"],
            ["drug_dosages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drug_categorizations_name"),
        "drug_categorizations",
        ["name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_drug_categorizations_name"), table_name="drug_categorizations"
    )
    op.drop_table("drug_categorizations")
    # ### end Alembic commands ###
