"""Tables for storing array values

Revision ID: 410779c77290
Revises: 
Create Date: 2022-05-25 09:43:46.436905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410779c77290'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_sensitivities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_drug1', sa.Numeric(), nullable=True),
    sa.Column('s_drug2', sa.Numeric(), nullable=True),
    sa.Column('r1_drug1', sa.Numeric(), nullable=True),
    sa.Column('r1_drug2', sa.Numeric(), nullable=True),
    sa.Column('r2_drug1', sa.Numeric(), nullable=True),
    sa.Column('r2_drug2', sa.Numeric(), nullable=True),
    sa.Column('r12_drug1', sa.Numeric(), nullable=True),
    sa.Column('r12_drug2', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_sensitivities_r12_drug1'), 'drug_sensitivities', ['r12_drug1'], unique=False)
    op.create_index(op.f('ix_drug_sensitivities_r12_drug2'), 'drug_sensitivities', ['r12_drug2'], unique=False)
    op.create_index(op.f('ix_drug_sensitivities_r1_drug1'), 'drug_sensitivities', ['r1_drug1'], unique=False)
    op.create_index(op.f('ix_drug_sensitivities_r1_drug2'), 'drug_sensitivities', ['r1_drug2'], unique=False)
    op.create_index(op.f('ix_drug_sensitivities_r2_drug1'), 'drug_sensitivities', ['r2_drug1'], unique=False)
    op.create_index(op.f('ix_drug_sensitivities_r2_drug2'), 'drug_sensitivities', ['r2_drug2'], unique=False)
    op.create_index(op.f('ix_drug_sensitivities_s_drug1'), 'drug_sensitivities', ['s_drug1'], unique=False)
    op.create_index(op.f('ix_drug_sensitivities_s_drug2'), 'drug_sensitivities', ['s_drug2'], unique=False)
    op.create_table('initial_populations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s', sa.Numeric(), nullable=True),
    sa.Column('r1', sa.Numeric(), nullable=True),
    sa.Column('r2', sa.Numeric(), nullable=True),
    sa.Column('r12', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initial_populations_r1'), 'initial_populations', ['r1'], unique=False)
    op.create_index(op.f('ix_initial_populations_r12'), 'initial_populations', ['r12'], unique=False)
    op.create_index(op.f('ix_initial_populations_r2'), 'initial_populations', ['r2'], unique=False)
    op.create_index(op.f('ix_initial_populations_s'), 'initial_populations', ['s'], unique=False)
    op.add_column('parameters', sa.Column('drug_sensitivities_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parameters', 'initial_populations', ['initial_subclone_population_id'], ['id'])
    op.create_foreign_key(None, 'parameters', 'drug_sensitivities', ['drug_sensitivities_id'], ['id'])
    op.drop_column('parameters', 'drug_senstivities_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('drug_senstivities_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parameters', type_='foreignkey')
    op.drop_constraint(None, 'parameters', type_='foreignkey')
    op.drop_column('parameters', 'drug_sensitivities_id')
    op.drop_index(op.f('ix_initial_populations_s'), table_name='initial_populations')
    op.drop_index(op.f('ix_initial_populations_r2'), table_name='initial_populations')
    op.drop_index(op.f('ix_initial_populations_r12'), table_name='initial_populations')
    op.drop_index(op.f('ix_initial_populations_r1'), table_name='initial_populations')
    op.drop_table('initial_populations')
    op.drop_index(op.f('ix_drug_sensitivities_s_drug2'), table_name='drug_sensitivities')
    op.drop_index(op.f('ix_drug_sensitivities_s_drug1'), table_name='drug_sensitivities')
    op.drop_index(op.f('ix_drug_sensitivities_r2_drug2'), table_name='drug_sensitivities')
    op.drop_index(op.f('ix_drug_sensitivities_r2_drug1'), table_name='drug_sensitivities')
    op.drop_index(op.f('ix_drug_sensitivities_r1_drug2'), table_name='drug_sensitivities')
    op.drop_index(op.f('ix_drug_sensitivities_r1_drug1'), table_name='drug_sensitivities')
    op.drop_index(op.f('ix_drug_sensitivities_r12_drug2'), table_name='drug_sensitivities')
    op.drop_index(op.f('ix_drug_sensitivities_r12_drug1'), table_name='drug_sensitivities')
    op.drop_table('drug_sensitivities')
    # ### end Alembic commands ###
