"""Create drug dosages table

Revision ID: 560b57c46b93
Revises: 21e0dddf3272
Create Date: 2022-05-31 09:53:00.623533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "560b57c46b93"
down_revision = "21e0dddf3272"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drug_dosages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parameter_id", sa.Integer(), nullable=True),
        sa.Column("strategy_id", sa.Integer(), nullable=True),
        sa.Column("t", sa.Integer(), nullable=True),
        sa.Column("drug_1", sa.Numeric(), nullable=True),
        sa.Column("drug_2", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(["parameter_id"], ["parameters.id"],),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategy.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drug_dosages_drug_1"), "drug_dosages", ["drug_1"], unique=False
    )
    op.create_index(
        op.f("ix_drug_dosages_drug_2"), "drug_dosages", ["drug_2"], unique=False
    )
    op.create_index(op.f("ix_drug_dosages_t"), "drug_dosages", ["t"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_drug_dosages_t"), table_name="drug_dosages")
    op.drop_index(op.f("ix_drug_dosages_drug_2"), table_name="drug_dosages")
    op.drop_index(op.f("ix_drug_dosages_drug_1"), table_name="drug_dosages")
    op.drop_table("drug_dosages")
    # ### end Alembic commands ###
