"""simulation output foreign keys

Revision ID: 6e5a69aaebc8
Revises: 515bc1e30f18
Create Date: 2022-05-17 10:48:13.335052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5a69aaebc8'
down_revision = '515bc1e30f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_output', sa.Column('strategy_id', sa.Integer(), nullable=True))
    op.add_column('simulation_output', sa.Column('parameter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'simulation_output', 'parameters', ['parameter_id'], ['id'])
    op.create_foreign_key(None, 'simulation_output', 'strategy', ['strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'simulation_output', type_='foreignkey')
    op.drop_constraint(None, 'simulation_output', type_='foreignkey')
    op.drop_column('simulation_output', 'parameter_id')
    op.drop_column('simulation_output', 'strategy_id')
    # ### end Alembic commands ###
