"""Create db tables

Revision ID: 8e44c2d99a18
Revises: 
Create Date: 2022-06-13 14:21:08.197903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8e44c2d99a18"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drug_sensitivities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("s_drug1", sa.Numeric(), nullable=True),
        sa.Column("s_drug2", sa.Numeric(), nullable=True),
        sa.Column("r1_drug1", sa.Numeric(), nullable=True),
        sa.Column("r1_drug2", sa.Numeric(), nullable=True),
        sa.Column("r2_drug1", sa.Numeric(), nullable=True),
        sa.Column("r2_drug2", sa.Numeric(), nullable=True),
        sa.Column("r12_drug1", sa.Numeric(), nullable=True),
        sa.Column("r12_drug2", sa.Numeric(), nullable=True),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drug_sensitivities_r12_drug1"),
        "drug_sensitivities",
        ["r12_drug1"],
        unique=False,
    )
    op.create_index(
        op.f("ix_drug_sensitivities_r12_drug2"),
        "drug_sensitivities",
        ["r12_drug2"],
        unique=False,
    )
    op.create_index(
        op.f("ix_drug_sensitivities_r1_drug1"),
        "drug_sensitivities",
        ["r1_drug1"],
        unique=False,
    )
    op.create_index(
        op.f("ix_drug_sensitivities_r1_drug2"),
        "drug_sensitivities",
        ["r1_drug2"],
        unique=False,
    )
    op.create_index(
        op.f("ix_drug_sensitivities_r2_drug1"),
        "drug_sensitivities",
        ["r2_drug1"],
        unique=False,
    )
    op.create_index(
        op.f("ix_drug_sensitivities_r2_drug2"),
        "drug_sensitivities",
        ["r2_drug2"],
        unique=False,
    )
    op.create_index(
        op.f("ix_drug_sensitivities_s_drug1"),
        "drug_sensitivities",
        ["s_drug1"],
        unique=False,
    )
    op.create_index(
        op.f("ix_drug_sensitivities_s_drug2"),
        "drug_sensitivities",
        ["s_drug2"],
        unique=False,
    )
    op.create_table(
        "initial_populations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("s", sa.Numeric(), nullable=True),
        sa.Column("r1", sa.Numeric(), nullable=True),
        sa.Column("r2", sa.Numeric(), nullable=True),
        sa.Column("r12", sa.Numeric(), nullable=True),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_initial_populations_r1"), "initial_populations", ["r1"], unique=False
    )
    op.create_index(
        op.f("ix_initial_populations_r12"), "initial_populations", ["r12"], unique=False
    )
    op.create_index(
        op.f("ix_initial_populations_r2"), "initial_populations", ["r2"], unique=False
    )
    op.create_index(
        op.f("ix_initial_populations_s"), "initial_populations", ["s"], unique=False
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategies_description"), "strategies", ["description"], unique=False
    )
    op.create_index(op.f("ix_strategies_name"), "strategies", ["name"], unique=False)
    op.create_table(
        "transition_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("s_s", sa.Numeric(), nullable=True),
        sa.Column("s_r1", sa.Numeric(), nullable=True),
        sa.Column("s_r2", sa.Numeric(), nullable=True),
        sa.Column("s_r12", sa.Numeric(), nullable=True),
        sa.Column("r1_s", sa.Numeric(), nullable=True),
        sa.Column("r1_r1", sa.Numeric(), nullable=True),
        sa.Column("r1_r2", sa.Numeric(), nullable=True),
        sa.Column("r1_r12", sa.Numeric(), nullable=True),
        sa.Column("r2_s", sa.Numeric(), nullable=True),
        sa.Column("r2_r1", sa.Numeric(), nullable=True),
        sa.Column("r2_r2", sa.Numeric(), nullable=True),
        sa.Column("r2_r12", sa.Numeric(), nullable=True),
        sa.Column("r12_s", sa.Numeric(), nullable=True),
        sa.Column("r12_r1", sa.Numeric(), nullable=True),
        sa.Column("r12_r2", sa.Numeric(), nullable=True),
        sa.Column("r12_r12", sa.Numeric(), nullable=True),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transition_rates_r12_r1"), "transition_rates", ["r12_r1"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_r12_r12"),
        "transition_rates",
        ["r12_r12"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transition_rates_r12_r2"), "transition_rates", ["r12_r2"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_r12_s"), "transition_rates", ["r12_s"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_r1_r1"), "transition_rates", ["r1_r1"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_r1_r12"), "transition_rates", ["r1_r12"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_r1_r2"), "transition_rates", ["r1_r2"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_r1_s"), "transition_rates", ["r1_s"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_r2_r1"), "transition_rates", ["r2_r1"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_r2_r12"), "transition_rates", ["r2_r12"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_r2_r2"), "transition_rates", ["r2_r2"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_r2_s"), "transition_rates", ["r2_s"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_s_r1"), "transition_rates", ["s_r1"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_s_r12"), "transition_rates", ["s_r12"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_s_r2"), "transition_rates", ["s_r2"], unique=False
    )
    op.create_index(
        op.f("ix_transition_rates_s_s"), "transition_rates", ["s_s"], unique=False
    )
    op.create_table(
        "parameters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("initial_subclone_population_id", sa.Integer(), nullable=True),
        sa.Column("growth_rate", sa.Numeric(), nullable=True),
        sa.Column("evolutionary_rates_id", sa.Integer(), nullable=True),
        sa.Column("drug_sensitivities_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["drug_sensitivities_id"],
            ["drug_sensitivities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evolutionary_rates_id"],
            ["transition_rates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["initial_subclone_population_id"],
            ["initial_populations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parameters_growth_rate"), "parameters", ["growth_rate"], unique=False
    )
    op.create_table(
        "drug_dosages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parameter_id", sa.Integer(), nullable=True),
        sa.Column("strategy_id", sa.Integer(), nullable=True),
        sa.Column("t", sa.Integer(), nullable=True),
        sa.Column("drug_1", sa.Numeric(), nullable=True),
        sa.Column("drug_2", sa.Numeric(), nullable=True),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["parameter_id"],
            ["parameters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drug_dosages_drug_1"), "drug_dosages", ["drug_1"], unique=False
    )
    op.create_index(
        op.f("ix_drug_dosages_drug_2"), "drug_dosages", ["drug_2"], unique=False
    )
    op.create_index(op.f("ix_drug_dosages_t"), "drug_dosages", ["t"], unique=False)
    op.create_table(
        "populations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parameter_id", sa.Integer(), nullable=True),
        sa.Column("strategy_id", sa.Integer(), nullable=True),
        sa.Column("t", sa.Integer(), nullable=True),
        sa.Column("s", sa.Numeric(), nullable=True),
        sa.Column("r1", sa.Numeric(), nullable=True),
        sa.Column("r2", sa.Numeric(), nullable=True),
        sa.Column("r12", sa.Numeric(), nullable=True),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["parameter_id"],
            ["parameters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_populations_r1"), "populations", ["r1"], unique=False)
    op.create_index(op.f("ix_populations_r12"), "populations", ["r12"], unique=False)
    op.create_index(op.f("ix_populations_r2"), "populations", ["r2"], unique=False)
    op.create_index(op.f("ix_populations_s"), "populations", ["s"], unique=False)
    op.create_index(op.f("ix_populations_t"), "populations", ["t"], unique=False)
    op.create_table(
        "stopping_times",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parameter_id", sa.Integer(), nullable=True),
        sa.Column("strategy_0", sa.Numeric(), nullable=True),
        sa.Column("strategy_1", sa.Numeric(), nullable=True),
        sa.Column("strategy_2_1", sa.Numeric(), nullable=True),
        sa.Column("strategy_2_2", sa.Numeric(), nullable=True),
        sa.Column("strategy_3", sa.Numeric(), nullable=True),
        sa.Column("strategy_1_dp", sa.Numeric(), nullable=True),
        sa.Column("strategy_2_1_dp", sa.Numeric(), nullable=True),
        sa.Column("strategy_2_2_dp", sa.Numeric(), nullable=True),
        sa.Column("strategy_3_dp", sa.Numeric(), nullable=True),
        sa.Column("global_dp", sa.Numeric(), nullable=True),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["parameter_id"],
            ["parameters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stopping_times_global_dp"),
        "stopping_times",
        ["global_dp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_0"),
        "stopping_times",
        ["strategy_0"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_1"),
        "stopping_times",
        ["strategy_1"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_1_dp"),
        "stopping_times",
        ["strategy_1_dp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_2_1"),
        "stopping_times",
        ["strategy_2_1"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_2_1_dp"),
        "stopping_times",
        ["strategy_2_1_dp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_2_2"),
        "stopping_times",
        ["strategy_2_2"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_2_2_dp"),
        "stopping_times",
        ["strategy_2_2_dp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_3"),
        "stopping_times",
        ["strategy_3"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stopping_times_strategy_3_dp"),
        "stopping_times",
        ["strategy_3_dp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stopping_times_strategy_3_dp"), table_name="stopping_times")
    op.drop_index(op.f("ix_stopping_times_strategy_3"), table_name="stopping_times")
    op.drop_index(
        op.f("ix_stopping_times_strategy_2_2_dp"), table_name="stopping_times"
    )
    op.drop_index(op.f("ix_stopping_times_strategy_2_2"), table_name="stopping_times")
    op.drop_index(
        op.f("ix_stopping_times_strategy_2_1_dp"), table_name="stopping_times"
    )
    op.drop_index(op.f("ix_stopping_times_strategy_2_1"), table_name="stopping_times")
    op.drop_index(op.f("ix_stopping_times_strategy_1_dp"), table_name="stopping_times")
    op.drop_index(op.f("ix_stopping_times_strategy_1"), table_name="stopping_times")
    op.drop_index(op.f("ix_stopping_times_strategy_0"), table_name="stopping_times")
    op.drop_index(op.f("ix_stopping_times_global_dp"), table_name="stopping_times")
    op.drop_table("stopping_times")
    op.drop_index(op.f("ix_populations_t"), table_name="populations")
    op.drop_index(op.f("ix_populations_s"), table_name="populations")
    op.drop_index(op.f("ix_populations_r2"), table_name="populations")
    op.drop_index(op.f("ix_populations_r12"), table_name="populations")
    op.drop_index(op.f("ix_populations_r1"), table_name="populations")
    op.drop_table("populations")
    op.drop_index(op.f("ix_drug_dosages_t"), table_name="drug_dosages")
    op.drop_index(op.f("ix_drug_dosages_drug_2"), table_name="drug_dosages")
    op.drop_index(op.f("ix_drug_dosages_drug_1"), table_name="drug_dosages")
    op.drop_table("drug_dosages")
    op.drop_index(op.f("ix_parameters_growth_rate"), table_name="parameters")
    op.drop_table("parameters")
    op.drop_index(op.f("ix_transition_rates_s_s"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_s_r2"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_s_r12"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_s_r1"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_r2_s"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_r2_r2"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_r2_r12"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_r2_r1"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_r1_s"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_r1_r2"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_r1_r12"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_r1_r1"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_r12_s"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_r12_r2"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_r12_r12"), table_name="transition_rates")
    op.drop_index(op.f("ix_transition_rates_r12_r1"), table_name="transition_rates")
    op.drop_table("transition_rates")
    op.drop_index(op.f("ix_strategies_name"), table_name="strategies")
    op.drop_index(op.f("ix_strategies_description"), table_name="strategies")
    op.drop_table("strategies")
    op.drop_index(op.f("ix_initial_populations_s"), table_name="initial_populations")
    op.drop_index(op.f("ix_initial_populations_r2"), table_name="initial_populations")
    op.drop_index(op.f("ix_initial_populations_r12"), table_name="initial_populations")
    op.drop_index(op.f("ix_initial_populations_r1"), table_name="initial_populations")
    op.drop_table("initial_populations")
    op.drop_index(
        op.f("ix_drug_sensitivities_s_drug2"), table_name="drug_sensitivities"
    )
    op.drop_index(
        op.f("ix_drug_sensitivities_s_drug1"), table_name="drug_sensitivities"
    )
    op.drop_index(
        op.f("ix_drug_sensitivities_r2_drug2"), table_name="drug_sensitivities"
    )
    op.drop_index(
        op.f("ix_drug_sensitivities_r2_drug1"), table_name="drug_sensitivities"
    )
    op.drop_index(
        op.f("ix_drug_sensitivities_r1_drug2"), table_name="drug_sensitivities"
    )
    op.drop_index(
        op.f("ix_drug_sensitivities_r1_drug1"), table_name="drug_sensitivities"
    )
    op.drop_index(
        op.f("ix_drug_sensitivities_r12_drug2"), table_name="drug_sensitivities"
    )
    op.drop_index(
        op.f("ix_drug_sensitivities_r12_drug1"), table_name="drug_sensitivities"
    )
    op.drop_table("drug_sensitivities")
    # ### end Alembic commands ###
