"""Add created and updated fields to tables

Revision ID: cf031e9a34db
Revises: 2cad1a2a27f3
Create Date: 2022-06-07 18:27:33.953763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf031e9a34db"
down_revision = "2cad1a2a27f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drug_dosages",
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "drug_dosages",
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "populations",
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "populations",
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "stopping_times",
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "stopping_times",
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.drop_index("ix_stopping_times_strategy_1", table_name="stopping_times")
    op.create_index(
        op.f("ix_stopping_times_strategy_1"),
        "stopping_times",
        ["strategy_1"],
        unique=False,
    )
    op.drop_index("ix_stopping_times_strategy_2_1", table_name="stopping_times")
    op.create_index(
        op.f("ix_stopping_times_strategy_2_1"),
        "stopping_times",
        ["strategy_2_1"],
        unique=False,
    )
    op.drop_index("ix_stopping_times_strategy_2_2", table_name="stopping_times")
    op.create_index(
        op.f("ix_stopping_times_strategy_2_2"),
        "stopping_times",
        ["strategy_2_2"],
        unique=False,
    )
    op.drop_index("ix_stopping_times_strategy_3", table_name="stopping_times")
    op.create_index(
        op.f("ix_stopping_times_strategy_3"),
        "stopping_times",
        ["strategy_3"],
        unique=False,
    )
    op.add_column(
        "strategies",
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "strategies",
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "transition_rates",
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "transition_rates",
        sa.Column(
            "updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transition_rates", "updated_on")
    op.drop_column("transition_rates", "created_on")
    op.drop_column("strategies", "updated_on")
    op.drop_column("strategies", "created_on")
    op.drop_index(op.f("ix_stopping_times_strategy_3"), table_name="stopping_times")
    op.create_index(
        "ix_stopping_times_strategy_3", "stopping_times", ["strategy_1"], unique=False
    )
    op.drop_index(op.f("ix_stopping_times_strategy_2_2"), table_name="stopping_times")
    op.create_index(
        "ix_stopping_times_strategy_2_2",
        "stopping_times",
        ["strategy_2_1"],
        unique=False,
    )
    op.drop_index(op.f("ix_stopping_times_strategy_2_1"), table_name="stopping_times")
    op.create_index(
        "ix_stopping_times_strategy_2_1",
        "stopping_times",
        ["strategy_2_2"],
        unique=False,
    )
    op.drop_index(op.f("ix_stopping_times_strategy_1"), table_name="stopping_times")
    op.create_index(
        "ix_stopping_times_strategy_1", "stopping_times", ["strategy_3"], unique=False
    )
    op.drop_column("stopping_times", "updated_on")
    op.drop_column("stopping_times", "created_on")
    op.drop_column("populations", "updated_on")
    op.drop_column("populations", "created_on")
    op.drop_column("drug_dosages", "updated_on")
    op.drop_column("drug_dosages", "created_on")
    # ### end Alembic commands ###
