"""Add more fields to db tables

Revision ID: d842039faf66
Revises: 11edf4a599b6
Create Date: 2022-05-17 11:44:37.673727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd842039faf66'
down_revision = '11edf4a599b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('growth_rate', sa.Numeric(), nullable=True))
    op.add_column('parameters', sa.Column('initial_subclone_populations', sa.Numeric(), nullable=True))
    op.add_column('parameters', sa.Column('evolutionary_rates', sa.Numeric(), nullable=True))
    op.add_column('parameters', sa.Column('drug_sensitivity', sa.Numeric(), nullable=True))
    op.create_index(op.f('ix_parameters_drug_sensitivity'), 'parameters', ['drug_sensitivity'], unique=False)
    op.create_index(op.f('ix_parameters_evolutionary_rates'), 'parameters', ['evolutionary_rates'], unique=False)
    op.create_index(op.f('ix_parameters_growth_rate'), 'parameters', ['growth_rate'], unique=False)
    op.create_index(op.f('ix_parameters_initial_subclone_populations'), 'parameters', ['initial_subclone_populations'], unique=False)
    op.add_column('simulation_output', sa.Column('subclone_populations', sa.Numeric(), nullable=True))
    op.add_column('simulation_output', sa.Column('drug_dosage', sa.Numeric(), nullable=True))
    op.add_column('simulation_output', sa.Column('stopping_time', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_simulation_output_drug_dosage'), 'simulation_output', ['drug_dosage'], unique=False)
    op.create_index(op.f('ix_simulation_output_stopping_time'), 'simulation_output', ['stopping_time'], unique=False)
    op.create_index(op.f('ix_simulation_output_subclone_populations'), 'simulation_output', ['subclone_populations'], unique=False)
    op.create_index(op.f('ix_strategy_description'), 'strategy', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_description'), table_name='strategy')
    op.drop_index(op.f('ix_simulation_output_subclone_populations'), table_name='simulation_output')
    op.drop_index(op.f('ix_simulation_output_stopping_time'), table_name='simulation_output')
    op.drop_index(op.f('ix_simulation_output_drug_dosage'), table_name='simulation_output')
    op.drop_column('simulation_output', 'stopping_time')
    op.drop_column('simulation_output', 'drug_dosage')
    op.drop_column('simulation_output', 'subclone_populations')
    op.drop_index(op.f('ix_parameters_initial_subclone_populations'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_growth_rate'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_evolutionary_rates'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_drug_sensitivity'), table_name='parameters')
    op.drop_column('parameters', 'drug_sensitivity')
    op.drop_column('parameters', 'evolutionary_rates')
    op.drop_column('parameters', 'initial_subclone_populations')
    op.drop_column('parameters', 'growth_rate')
    # ### end Alembic commands ###
