"""Add categorization column to table

Revision ID: dbcaef11b15e
Revises: 2d551030b847
Create Date: 2022-06-22 22:55:38.698417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = "dbcaef11b15e"
down_revision = "2d551030b847"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    trialoutcome = ENUM(
        "BOTH_SAME", "FIRST_SAME", "SECOND_SAME", "NONE_SAME", name="trialoutcome"
    )
    trialoutcome.create(op.get_bind())
    op.add_column(
        "drug_categorizations", sa.Column("categorization", trialoutcome, nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("drug_categorizations", "categorization")
    op.execute("DROP TYPE trialoutcome")
    # ### end Alembic commands ###
