"""Drop name field from categorization table

Revision ID: e2b298e4eba0
Revises: dbcaef11b15e
Create Date: 2022-06-23 07:06:57.658625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2b298e4eba0"
down_revision = "dbcaef11b15e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_drug_categorizations_name", table_name="drug_categorizations")
    op.drop_column("drug_categorizations", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drug_categorizations",
        sa.Column("name", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    )
    op.create_index(
        "ix_drug_categorizations_name", "drug_categorizations", ["name"], unique=False
    )
    # ### end Alembic commands ###
