"""Create populations table

Revision ID: fec1154090c0
Revises: 560b57c46b93
Create Date: 2022-05-31 16:54:40.735267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec1154090c0'
down_revision = '560b57c46b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('populations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('t', sa.Integer(), nullable=True),
    sa.Column('s', sa.Numeric(), nullable=True),
    sa.Column('r1', sa.Numeric(), nullable=True),
    sa.Column('r2', sa.Numeric(), nullable=True),
    sa.Column('r12', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_populations_r1'), 'populations', ['r1'], unique=False)
    op.create_index(op.f('ix_populations_r12'), 'populations', ['r12'], unique=False)
    op.create_index(op.f('ix_populations_r2'), 'populations', ['r2'], unique=False)
    op.create_index(op.f('ix_populations_s'), 'populations', ['s'], unique=False)
    op.create_index(op.f('ix_populations_t'), 'populations', ['t'], unique=False)
    op.drop_index('ix_strategy_description', table_name='strategies')
    op.create_index(op.f('ix_strategies_description'), 'strategies', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategies_description'), table_name='strategies')
    op.create_index('ix_strategy_description', 'strategies', ['description'], unique=False)
    op.drop_index(op.f('ix_populations_t'), table_name='populations')
    op.drop_index(op.f('ix_populations_s'), table_name='populations')
    op.drop_index(op.f('ix_populations_r2'), table_name='populations')
    op.drop_index(op.f('ix_populations_r12'), table_name='populations')
    op.drop_index(op.f('ix_populations_r1'), table_name='populations')
    op.drop_table('populations')
    # ### end Alembic commands ###
